target-version = "py311"
[lint]
select = ["A", "ASYNC", "I", "E", "F", "B", "C4", "T10", "T20", "EM", "ISC", "S"]
ignore = ["E501", "ISC001"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

exclude = [
    ".git",
    "__pycache__",
    "lib",
    "bin",
    "include"
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"connectors/*" = ["S608"]
"scripts/verify.py" = [ "EM" ]
"setup.py" = [ "EM" ]
"tests/*" = ["B017", "S101", "S"]
"tests/conftest.py" = [ "EM" ]

[lint.isort]
known-first-party=["connectors", "tests"]
